









# Example configuration entry
#web_server:
#  port: 80


# Enable logging
logger:
  level: DEBUG


uart:
  id: uart_bus
  rx_pin: GPIO19
#  tx_pin: ${tx_pin}
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 512


sensor:
  - platform: template
    name: "Cell 1"
    id: cell_1
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 2"
    id: cell_2
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 3"
    id: cell_3
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 4"
    id: cell_4
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 5"
    id: cell_5
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 6"
    id: cell_6
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 7"
    id: cell_7
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 8"
    id: cell_8
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 9"
    id: cell_9
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 10"
    id: cell_10
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 11"
    id: cell_11
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 12"
    id: cell_12
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 13"
    id: cell_13
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 14"
    id: cell_14
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 15"
    id: cell_15
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 16"
    id: cell_16
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "Battery Min Cell"
    id: battery_min_cell
    unit_of_measurement: "V"
    accuracy_decimals: 3
    force_update: true
    icon: "mdi:battery-arrow-down"
  - platform: template
    name: "Battery Max Cell"
    id: battery_max_cell
    unit_of_measurement: "V"
    accuracy_decimals: 3
    icon: "mdi:battery-arrow-up"
  - platform: template
    name: "Battery Delta"
    id: battery_delta
    unit_of_measurement: "V"
    accuracy_decimals: 3
    icon: "mdi:vector-difference"
    
  - platform: template
    name: "Battery Total Voltage"
    id: battery_total_voltage
    unit_of_measurement: "V"
    accuracy_decimals: 2
    device_class: voltage

  - platform: template
    name: "Aferiy SoC"
    id: aferiy_soc
    unit_of_measurement: "%"
    accuracy_decimals: 0
    device_class: battery
    state_class: measurement

  - platform: template
    name: "Battery Current"
    id: battery_current
    unit_of_measurement: "A"
    accuracy_decimals: 2
    device_class: current

  - platform: template
    name: "Temp 1"
    id: temp_1
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature

  - platform: template
    name: "Temp 2"
    id: temp_2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature

text_sensor:
  - platform: template
    name: "Aferiy Status"
    update_interval: 500ms 
    lambda: |-
      static std::vector<uint8_t> buffer;
      while (id(uart_bus).available()) {
        uint8_t b;
        id(uart_bus).read_byte(&b);
        buffer.push_back(b);
        if (buffer.size() > 512) buffer.erase(buffer.begin());
      }

      for (size_t i = 0; i < buffer.size(); i++) {
        
        // --- 1. НАПРУГА БАТАРЕЇ (Маркер 14 AD або подібний) ---
        if (i + 1 < buffer.size() && buffer[i] == 0x14 && buffer[i+1] >= 0xA0) {
            float total_v = ((uint16_t(buffer[i]) << 8) | buffer[i+1]) / 100.0;
            if (total_v > 40.0 && total_v < 60.0) {
                id(battery_total_voltage).publish_state(total_v);
            }
        }

        // --- 2. НАПРУГИ КОМІРОК (Шукаємо блок 11 04 ... 0C) ---
        // У дампі: 11 04 00 00 00 3C [0C ED 0C ED ...]
        if (i + 38 < buffer.size() && buffer[i] == 0x11 && buffer[i+1] == 0x04) {
            size_t c_start = i + 6; // Комірки починаються через 6 байтів після 11 04
            
            // Перевіряємо чи там дійсно напруги (починаються з 0C або 0D)
            if (buffer[c_start] == 0x0C || buffer[c_start] == 0x0D) {
                auto get_cv = [&](int idx) { return ((uint16_t(buffer[idx]) << 8) | buffer[idx+1]) / 1000.0; };
                
                id(cell_1).publish_state(get_cv(c_start));     id(cell_2).publish_state(get_cv(c_start+2));
                id(cell_3).publish_state(get_cv(c_start+4));   id(cell_4).publish_state(get_cv(c_start+6));
                id(cell_5).publish_state(get_cv(c_start+8));   id(cell_6).publish_state(get_cv(c_start+10));
                id(cell_7).publish_state(get_cv(c_start+12));  id(cell_8).publish_state(get_cv(c_start+14));
                id(cell_9).publish_state(get_cv(c_start+16));  id(cell_10).publish_state(get_cv(c_start+18));
                id(cell_11).publish_state(get_cv(c_start+20)); id(cell_12).publish_state(get_cv(c_start+22));
                id(cell_13).publish_state(get_cv(c_start+24)); id(cell_14).publish_state(get_cv(c_start+26));
                id(cell_15).publish_state(get_cv(c_start+28)); id(cell_16).publish_state(get_cv(c_start+30));
                
                // Дельта для контролю
                float mn = get_cv(c_start), mx = get_cv(c_start);
                for(int n=0; n<32; n+=2) {
                    float v = get_cv(c_start+n);
                    if (v < mn) mn = v;
                    if (v > mx) mx = v;
                }
                id(battery_min_cell).publish_state(mn);
                id(battery_max_cell).publish_state(mx);
                id(battery_delta).publish_state(mx - mn);
            }
        }

        // --- 3. SOC (Відсоток заряду) ---
        // Шукаємо дублі в кінці пакету (напр. 5D 5D)
        if (i + 1 < buffer.size() && buffer[i] == buffer[i+1] && buffer[i] > 5 && buffer[i] <= 100) {
            // Фільтруємо системні байти, щоб не плутати з комірками (0x0C)
            if (buffer[i] != 0x0C && buffer[i] != 0x0D && buffer[i] != 0x11 && buffer[i] != 0x14) {
                id(aferiy_soc).publish_state(buffer[i]);
            }
        }
      }
      return {"OK"};
