









# Example configuration entry
#web_server:
#  port: 80


# Enable logging
logger:
  level: DEBUG


uart:
  id: uart_bus
  rx_pin: GPIO19
#  tx_pin: ${tx_pin}
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 512

# =========================
# SENSORS
# =========================

sensor:

  # --- 16 CELL VOLTAGES ---
  - platform: template
    name: "Cell 1"
    id: cell_1
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement

  - platform: template
    name: "Cell 2"
    id: cell_2
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement

  - platform: template
    name: "Cell 3"
    id: cell_3
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement

  - platform: template
    name: "Cell 4"
    id: cell_4
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement

  - platform: template
    name: "Cell 5"
    id: cell_5
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement

  - platform: template
    name: "Cell 6"
    id: cell_6
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement

  - platform: template
    name: "Cell 7"
    id: cell_7
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement

  - platform: template
    name: "Cell 8"
    id: cell_8
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement

  - platform: template
    name: "Cell 9"
    id: cell_9
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement

  - platform: template
    name: "Cell 10"
    id: cell_10
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement

  - platform: template
    name: "Cell 11"
    id: cell_11
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement

  - platform: template
    name: "Cell 12"
    id: cell_12
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement

  - platform: template
    name: "Cell 13"
    id: cell_13
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement

  - platform: template
    name: "Cell 14"
    id: cell_14
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement

  - platform: template
    name: "Cell 15"
    id: cell_15
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement

  - platform: template
    name: "Cell 16"
    id: cell_16
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement


  # --- PACK VALUES ---
  - platform: template
    name: "Battery Voltage"
    id: battery_voltage
    unit_of_measurement: "V"
    accuracy_decimals: 2
    device_class: voltage
    state_class: measurement

  - platform: template
    name: "Battery Current"
    id: battery_current
    unit_of_measurement: "A"
    accuracy_decimals: 2
    device_class: current
    state_class: measurement

  - platform: template
    name: "Battery Power"
    id: battery_power
    unit_of_measurement: "W"
    accuracy_decimals: 1
    device_class: power
    state_class: measurement

  - platform: template
    name: "Battery Delta"
    id: delta_cell
    unit_of_measurement: "V"
    accuracy_decimals: 3
    state_class: measurement



# =========================
# BINARY SENSORS
# =========================

binary_sensor:
  - platform: template
    name: "BMS Overvoltage"
    id: alarm_ov

  - platform: template
    name: "BMS Undervoltage"
    id: alarm_uv

  - platform: template
    name: "Balancing Active"
    id: balancing_active


# =========================
# FRAME PARSER
# =========================

interval:
  - interval: 200ms
    then:
      - lambda: |-
          static std::vector<uint8_t> buffer;

          while (id(uart_bus).available()) {
            uint8_t b;
            id(uart_bus).read_byte(&b);
            buffer.push_back(b);
            if (buffer.size() > 300)
              buffer.erase(buffer.begin());
          }

          if (buffer.size() < 60)
            return;

          for (size_t i = 0; i < buffer.size() - 50; i++) {

            if (buffer[i] == 0x11 && buffer[i+1] == 0x04) {

              int start = i + 5;
              if (start + 40 >= buffer.size())
                continue;

              auto get_v = [&](int idx) {
                return ((uint16_t(buffer[idx+1]) << 8) | buffer[idx]) / 1000.0;
              };

              float cells[16];
              for (int c = 0; c < 16; c++)
                cells[c] = get_v(start + c*2);

              if (cells[0] < 2.0 || cells[0] > 4.0)
                continue;

              float min_v = cells[0];
              float max_v = cells[0];
              float total_v = 0;

              for (int c = 0; c < 16; c++) {
                total_v += cells[c];
                if (cells[c] < min_v) min_v = cells[c];
                if (cells[c] > max_v) max_v = cells[c];
              }

              id(cell_1).publish_state(cells[0]);
              id(cell_2).publish_state(cells[1]);
              id(cell_3).publish_state(cells[2]);
              id(cell_4).publish_state(cells[3]);
              id(cell_5).publish_state(cells[4]);
              id(cell_6).publish_state(cells[5]);
              id(cell_7).publish_state(cells[6]);
              id(cell_8).publish_state(cells[7]);
              id(cell_9).publish_state(cells[8]);
              id(cell_10).publish_state(cells[9]);
              id(cell_11).publish_state(cells[10]);
              id(cell_12).publish_state(cells[11]);
              id(cell_13).publish_state(cells[12]);
              id(cell_14).publish_state(cells[13]);
              id(cell_15).publish_state(cells[14]);
              id(cell_16).publish_state(cells[15]);

              id(delta_cell).publish_state(max_v - min_v);
              id(battery_voltage).publish_state(total_v);

              int16_t current_raw = (int16_t)((buffer[start+39] << 8) | buffer[start+38]);
              float current = current_raw / 100.0;

              id(battery_current).publish_state(current);

              id(battery_power).publish_state(total_v * current);

              uint16_t alarm = (buffer[start+35] << 8) | buffer[start+34];
              id(alarm_ov).publish_state(alarm & 0x0001);
              id(alarm_uv).publish_state(alarm & 0x0002);

              uint16_t balance_mask = (buffer[start+37] << 8) | buffer[start+36];
              id(balancing_active).publish_state(balance_mask != 0);



              buffer.clear();
              return;
            }
          }
