









# Example configuration entry
#web_server:
#  port: 80


# Enable logging
logger:
  level: DEBUG


uart:
  id: uart_bus
  rx_pin: GPIO19
#  tx_pin: ${tx_pin}
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 512


sensor:
  - platform: template
    name: "Cell 1"
    id: cell_1
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 2"
    id: cell_2
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 3"
    id: cell_3
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 4"
    id: cell_4
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 5"
    id: cell_5
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 6"
    id: cell_6
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 7"
    id: cell_7
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 8"
    id: cell_8
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 9"
    id: cell_9
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 10"
    id: cell_10
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 11"
    id: cell_11
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 12"
    id: cell_12
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 13"
    id: cell_13
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 14"
    id: cell_14
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 15"
    id: cell_15
    unit_of_measurement: "V"
    accuracy_decimals: 3
  - platform: template
    name: "Cell 16"
    id: cell_16
    unit_of_measurement: "V"
    accuracy_decimals: 3
    
  - platform: template
    name: "Battery Min Cell"
    id: battery_min_cell
    unit_of_measurement: "V"
    accuracy_decimals: 3
    force_update: true
    icon: "mdi:battery-arrow-down"
  - platform: template
    name: "Battery Max Cell"
    id: battery_max_cell
    unit_of_measurement: "V"
    accuracy_decimals: 3
    icon: "mdi:battery-arrow-up"
  - platform: template
    name: "Battery Delta"
    id: battery_delta
    unit_of_measurement: "V"
    accuracy_decimals: 3
    icon: "mdi:vector-difference"
    
  - platform: template
    name: "Battery Total Voltage"
    id: battery_total_voltage
    unit_of_measurement: "V"
    accuracy_decimals: 2
    device_class: voltage

  - platform: template
    name: "Aferiy SoC"
    id: aferiy_soc
    unit_of_measurement: "%"
    accuracy_decimals: 0
    device_class: battery
    state_class: measurement

  - platform: template
    name: "Battery Current"
    id: battery_current
    unit_of_measurement: "A"
    accuracy_decimals: 2
    device_class: current

  - platform: template
    name: "Temp 1"
    id: temp_1
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature

  - platform: template
    name: "Temp 2"
    id: temp_2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature

text_sensor:
  - platform: template
    name: "Aferiy Status"
    update_interval: 500ms 
    lambda: |-
      static std::vector<uint8_t> buffer;
      while (id(uart_bus).available()) {
        uint8_t b;
        id(uart_bus).read_byte(&b);
        buffer.push_back(b);
        if (buffer.size() > 450) buffer.erase(buffer.begin());
      }

      for (size_t i = 0; i < buffer.size(); i++) {
        
        // --- БЛОК 1: КОМІРКИ (Твій робочий код) ---
        if (i + 3 < buffer.size() && buffer[i] == 0x10 && buffer[i+1] == 0x01 && buffer[i+2] == 0x01 && buffer[i+3] == 0x83) {
          if (i >= 64) {
            int start_idx = i - 64;
            auto get_v = [&](int idx) { return ((uint16_t(buffer[idx]) << 8) | buffer[idx+1]) / 1000.0; };
            float c[16];
            for (int j = 0; j < 16; j++) c[j] = get_v(start_idx + (j * 2));

            id(cell_1).publish_state(c[0]);   id(cell_2).publish_state(c[1]);
            id(cell_3).publish_state(c[2]);   id(cell_4).publish_state(c[3]);
            id(cell_5).publish_state(c[4]);   id(cell_6).publish_state(c[5]);
            id(cell_7).publish_state(c[6]);   id(cell_8).publish_state(c[7]);
            id(cell_9).publish_state(c[8]);   id(cell_10).publish_state(c[9]);
            id(cell_11).publish_state(c[10]); id(cell_12).publish_state(c[11]);
            id(cell_13).publish_state(c[12]); id(cell_14).publish_state(c[13]);
            id(cell_15).publish_state(c[14]); id(cell_16).publish_state(c[15]);

            float mn = c[0], mx = c[0];
            for (int j = 1; j < 16; j++) {
                if (c[j] < mn) mn = c[j];
                if (c[j] > mx) mx = c[j];
            }
            if (mn > 2.0 && mx < 4.5) {
                id(battery_min_cell).publish_state(mn);
                id(battery_max_cell).publish_state(mx);
                id(battery_delta).publish_state(mx - mn);
            }
          }
        }

        // --- БЛОК 2: НАПРУГА (Твій робочий код) ---
        if (i + 12 < buffer.size() && buffer[i] == 0x04 && buffer[i+4] == 0x18) {
            float total_v = ((uint16_t(buffer[i+11]) << 8) | buffer[i+12]) / 100.0;
            if (total_v > 40.0 && total_v < 60.0) {
                id(battery_total_voltage).publish_state(total_v);
            }
        }

        // --- БЛОК 3: SOC (Додаємо пошук відсотків) ---
        // SoC зазвичай іде в тому ж пакеті, де маркер 10 01 01 83
        if (i + 30 < buffer.size() && buffer[i] == 0x10 && buffer[i+1] == 0x01 && buffer[i+2] == 0x01 && buffer[i+3] == 0x83) {
            // Шукаємо дві однакові цифри (наприклад, 61 61) у зоні після маркера
            for (size_t k = i + 20; k < i + 30 && k + 1 < buffer.size(); k++) {
                if (buffer[k] == buffer[k+1] && buffer[k] > 0 && buffer[k] <= 100) {
                    id(aferiy_soc).publish_state(buffer[k]);
                    
                    // Після успішного зчитування SoC можна почистити буфер
                    buffer.erase(buffer.begin(), buffer.begin() + k);
                    return {"All Data Updated"};
                }
            }
        }
      }
      return {"Scanning..."};
